//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: common_guider.proto
namespace Common
{
    [global::ProtoBuf.ProtoContract(Name=@"GuiderMsgCmd")]
    public enum GuiderMsgCmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID", Value=0)]
      INVALID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPEN", Value=1)]
      OPEN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLOSE", Value=2)]
      CLOSE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Reopen", Value=3)]
      Reopen = 3
    }
  
}