//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: common_guider.proto
namespace Common
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vec3")]
  public partial class Vec3 : global::ProtoBuf.IExtensible
  {
    public Vec3() {}
    

    private float? _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x?? default(float); }
      set { _x = value; }
    }
    //Here has been deleted XmlIgnore
    [global::System.ComponentModel.Browsable(false)]
    public bool xSpecified
    {
      get { return _x != null; }
      set { if (value == (_x== null)) _x = value ? x : (float?)null; }
    }
    private bool ShouldSerializex() { return xSpecified; }
    private void Resetx() { xSpecified = false; }
    

    private float? _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y?? default(float); }
      set { _y = value; }
    }
    //Here has been deleted XmlIgnore
    [global::System.ComponentModel.Browsable(false)]
    public bool ySpecified
    {
      get { return _y != null; }
      set { if (value == (_y== null)) _y = value ? y : (float?)null; }
    }
    private bool ShouldSerializey() { return ySpecified; }
    private void Resety() { ySpecified = false; }
    

    private float? _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z?? default(float); }
      set { _z = value; }
    }
    //Here has been deleted XmlIgnore
    [global::System.ComponentModel.Browsable(false)]
    public bool zSpecified
    {
      get { return _z != null; }
      set { if (value == (_z== null)) _z = value ? z : (float?)null; }
    }
    private bool ShouldSerializez() { return zSpecified; }
    private void Resetz() { zSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuiderEvent")]
  public partial class GuiderEvent : global::ProtoBuf.IExtensible
  {
    public GuiderEvent() {}
    

    private string _name;
    /// <summary>
    /// 事件名
    /// </summary>
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    //Here has been deleted XmlIgnore
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return _name != null; }
      set { if (value == (_name== null)) _name = value ? name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    

    private string _par;
    /// <summary>
    /// 参数
    /// </summary>
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"par", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string par
    {
      get { return _par?? ""; }
      set { _par = value; }
    }
    //Here has been deleted XmlIgnore
    [global::System.ComponentModel.Browsable(false)]
    public bool parSpecified
    {
      get { return _par != null; }
      set { if (value == (_par== null)) _par = value ? par : (string)null; }
    }
    private bool ShouldSerializepar() { return parSpecified; }
    private void Resetpar() { parSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuiderMsgCmd")]
    public enum GuiderMsgCmd
    {
            
      /// <summary>
      /// 默认值
      /// </summary>
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CMD_INVALID", Value=0)]
      MSG_CMD_INVALID = 0,
            
      /// <summary>
      /// 开启
      /// </summary>
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CMD_OPEN", Value=1)]
      MSG_CMD_OPEN = 1,
            
      /// <summary>
      /// 结束
      /// </summary>
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CMD_CLOSE", Value=2)]
      MSG_CMD_CLOSE = 2,
            
      /// <summary>
      /// 重做当前引导
      /// </summary>
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CMD_Reopen", Value=3)]
      MSG_CMD_Reopen = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuiderTriggerType")]
    public enum GuiderTriggerType
    {
            
      /// <summary>
      /// 非法
      /// </summary>
      [global::ProtoBuf.ProtoEnum(Name=@"TRIGGER_INVALID", Value=0)]
      TRIGGER_INVALID = 0,
            
      /// <summary>
      /// 自动
      /// </summary>
      [global::ProtoBuf.ProtoEnum(Name=@"TRIGGER_AUTO", Value=1)]
      TRIGGER_AUTO = 1,
            
      /// <summary>
      /// 消息
      /// </summary>
      [global::ProtoBuf.ProtoEnum(Name=@"TRIGGER_MSG", Value=2)]
      TRIGGER_MSG = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuiderFollowType")]
    public enum GuiderFollowType
    {
            
      /// <summary>
      /// 一次
      /// </summary>
      [global::ProtoBuf.ProtoEnum(Name=@"FOLLOW_ONCE", Value=0)]
      FOLLOW_ONCE = 0,
            
      /// <summary>
      /// 定时
      /// </summary>
      [global::ProtoBuf.ProtoEnum(Name=@"FOLLOW_TIME", Value=1)]
      FOLLOW_TIME = 1,
            
      /// <summary>
      /// 每帧
      /// </summary>
      [global::ProtoBuf.ProtoEnum(Name=@"FOLLOW_FRAME", Value=2)]
      FOLLOW_FRAME = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuiderAnimType")]
    public enum GuiderAnimType
    {
            
      /// <summary>
      /// 无
      /// </summary>
      [global::ProtoBuf.ProtoEnum(Name=@"ANIM_TYPE_NONE", Value=0)]
      ANIM_TYPE_NONE = 0,
            
      /// <summary>
      /// 附加
      /// </summary>
      [global::ProtoBuf.ProtoEnum(Name=@"ANIM_TYPE_ATTACH", Value=1)]
      ANIM_TYPE_ATTACH = 1,
            
      /// <summary>
      /// 对应动画id
      /// </summary>
      [global::ProtoBuf.ProtoEnum(Name=@"ANIM_TYPE_CLICK", Value=10)]
      ANIM_TYPE_CLICK = 10
    }
  
}