//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: common_guider.proto
namespace Common
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vec3")]
  public partial class Vec3 : global::ProtoBuf.IExtensible
  {
    public Vec3() {}
    

    private float? _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x?? default(float); }
      set { _x = value; }
    }
    //Here has been deleted XmlIgnore
    [global::System.ComponentModel.Browsable(false)]
    public bool xSpecified
    {
      get { return _x != null; }
      set { if (value == (_x== null)) _x = value ? x : (float?)null; }
    }
    private bool ShouldSerializex() { return xSpecified; }
    private void Resetx() { xSpecified = false; }
    

    private float? _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y?? default(float); }
      set { _y = value; }
    }
    //Here has been deleted XmlIgnore
    [global::System.ComponentModel.Browsable(false)]
    public bool ySpecified
    {
      get { return _y != null; }
      set { if (value == (_y== null)) _y = value ? y : (float?)null; }
    }
    private bool ShouldSerializey() { return ySpecified; }
    private void Resety() { ySpecified = false; }
    

    private float? _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z?? default(float); }
      set { _z = value; }
    }
    //Here has been deleted XmlIgnore
    [global::System.ComponentModel.Browsable(false)]
    public bool zSpecified
    {
      get { return _z != null; }
      set { if (value == (_z== null)) _z = value ? z : (float?)null; }
    }
    private bool ShouldSerializez() { return zSpecified; }
    private void Resetz() { zSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuiderMsgCmd")]
    public enum GuiderMsgCmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CMD_INVALID", Value=0)]
      MSG_CMD_INVALID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CMD_OPEN", Value=1)]
      MSG_CMD_OPEN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CMD_CLOSE", Value=2)]
      MSG_CMD_CLOSE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CMD_Reopen", Value=3)]
      MSG_CMD_Reopen = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuiderTriggerType")]
    public enum GuiderTriggerType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRIGGER_INVALID", Value=0)]
      TRIGGER_INVALID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRIGGER_AUTO", Value=1)]
      TRIGGER_AUTO = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRIGGER_MSG", Value=2)]
      TRIGGER_MSG = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRIGGER_CLICK_MASK", Value=3)]
      TRIGGER_CLICK_MASK = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuiderAnimType")]
    public enum GuiderAnimType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ANIM_TYPE_NONE", Value=0)]
      ANIM_TYPE_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ANIM_TYPE_CLICK", Value=1)]
      ANIM_TYPE_CLICK = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ANIM_TYPE_ATTACH", Value=2)]
      ANIM_TYPE_ATTACH = 2
    }
  
}