# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_GUIDERMSGCMD = descriptor.EnumDescriptor(
  name='GuiderMsgCmd',
  full_name='Common.GuiderMsgCmd',
  filename='GuiderMsgCmd',
  values=[
    descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OPEN', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CLOSE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='Reopen', index=3, number=3,
      options=None,
      type=None),
  ],
  options=None,
)


INVALID = 0
OPEN = 1
CLOSE = 2
Reopen = 3




